version: '3.8'

services:
  mongodb_container: 
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend

  api_container:
    depends_on: 
      - mongodb_container
    image: api-node
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - "C:\\source\\api-node-docker:/src"
    networks:
      - backend

volumes:
  mongodb_data_container:

networks:
  backend:
